name: "Test Python"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python, Wagtail and Django
# - at least one test run for older supported version of Python, Wagtail and Django
# - a test run against Django's git main branch (allowing failures)
# - a test run against Wagtail's git main branch (allowing failures)

# Current configuration:
# - python 3.9, django 3.2, wagtail 2.14 (+ linting and other checks)
# - python 3.8, django 3.1, wagtail 2.13
# - python 3.7, django 3.1, wagtail 2.12

jobs:
  test-latest-supported:
    name: With latest supported Django and Wagtail
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "Django>=4.1,<4.2"
          pip install "Wagtail>4.1,<4.2"
      - name: âœ… Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: ðŸ§ª Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=importo

  test-legacy:
    name: With legacy Django and Wagtail
    needs: test-latest-supported
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    strategy:
      matrix:
        include:
          - python: 3.9
            wagtail: "Wagtail>=3.0,<4.0"
            django: Django>=4.0,<4.1
          - python: 3.9
            wagtail: "Wagtail>=2.16,<3.0"
            django: Django>=3.2,<4.0
          - python: 3.8
            wagtail: "Wagtail>=2.16,<3.0"
            django: Django>=3.1,<3.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest

  test-bleading-edges:
    name: With bleading-edge Django and Wagtail
    needs: test-legacy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
            wagtail: Wagtail>4.1,<4.2
          - django: Django>=4.1,<4.2
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest
