name: "Test Python"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python, Wagtail and Django
# - at least one test run for older supported version of Python, Wagtail and Django
# - a test run against Django's git main branch (allowing failures)
# - a test run against Wagtail's git main branch (allowing failures)

jobs:
  test-latest-supported:
    name: Latest Django + Wagtail
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "Django>=4.2,<4.3"
          pip install "Wagtail>5,<6"
      - name: âœ… Run django checks
        run: django-admin check
      - name: âœ… Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: ðŸ§ª Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=importo

  test-legacy:
    name: Legacy Django + Wagtail
    needs: test-latest-supported
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    strategy:
      matrix:
        include:

          - python: '3.10'
            wagtail: "Wagtail>=4,<5"
            django: Django>=4.1,<4.2
          - python: '3.9'
            wagtail: "Wagtail>=3,<4"
            django: Django>=4.0,<4.1
          - python: '3.9'
            wagtail: "Wagtail>=2,<3"
            django: Django>=3.2,<4.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest

  test-bleading-edges:
    name: Bleading-edge Django + Wagtail
    needs: test-legacy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DJANGO_SETTINGS_MODULE: importo.testapp.settings
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
            wagtail: Wagtail>4.1,<4.2
          - django: Django>=4.1,<4.2
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest
